on:
  workflow_dispatch:
    inputs:
      likes:
        description: "Likes"
        required: true
        default: "JSON d'objets Like"
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: sudo npm install -g npm@latest
      - run: npm i
      - run: echo $WORKFLOW_INPUT
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: echo $WORKFLOW_INPUT > likes.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out.mp4
